- name: Check if {{ stack_name }} stack exists
  command: "openstack stack show {{ stack_name }}"
  ignore_errors: yes
  register: stack_check

- name: Create heat stack {{ stack_name }}
  stack_create:
    name: "{{ stack_name }}"
    template: "{{ heat_template_path }}"
    parameters:
      master_hostname: "{{ master_hostname }}"
      capsule_hostname_prefix: "{{ capsule_hostname_prefix }}"
      satellite_domain_name: "{{ satellite_domain_name }}"
      external_network: "{{ external_network }}"
      service_network: "{{ service_network }}"
      service_subnet: "{{ service_subnet }}"
      ssh_user: "{{ ssh_user }}"
      satellite_ssh_key_name: "{{ satellite_ssh_key_name }}"
      master_image: "{{ master_image }}"
      capsule_image: "{{ capsule_image }}"
      master_volume_size: "{{ master_volume_size }}"
      capsule_volume_size: "{{ capsule_volume_size }}"
      master_flavor: "{{ master_flavor }}"
      capsule_flavor: "{{ capsule_flavor }}"
      capsule_count: "{{ capsule_count }}"
      capsule_server_group_policies: "{{ capsule_server_group_policies }}"
  register: stack_output
  when: stack_check.rc != 0
