- name: Check if instance exists
  shell:  openstack server show {{ instance_name }}
  register: instance_output
  ignore_errors: true

- name: Create OpenStack Instance
  shell: openstack server create --flavor {{ instance_flavor }} --image "{{ instance_image }}" --network {{ instance_network }} --key-name {{ instance_ssh_key_name }} --security-group {{ instance_security_group }} {{ instance_name }} --wait
  when: instance_output.rc != 0

- name: Get instance IP
  shell: openstack server show {{ instance_name }} |grep addresses |awk '{print $4'} |sed 's/{{ instance_network }}=//' |sed 's/,//'
  register: ip_output

- debug:
    msg: "Instance ip {{ ip_output.stdout }}"
  when: debug == True

- name: Add the instance to the inventory
  add_host:
    name: "{{ instance_name }}"
    groups: all,instance
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ ip_output.stdout }}"

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ip_output.stdout|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10

- debug:
    var: groups
  when: debug == True
