---
- name: Deploy Satellite Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: http://{{ openstack_ip }}:5000/v3
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3

  tasks:
  - import_role:
      name: osp-stack-create
  - import_role:
      name: osp-inventory
    tags: ['inventory']

- name: Perform base configuration of systems
  hosts: master
  become: true
  gather_facts: true

  tasks:
  - import_role:
      name: base
    tags: ['base']
  - import_role:
      name: sat6-prep
    tags: ['prep']

- name: Install Satellite 6
  hosts: master
  become: true
  gather_facts: true
  remote_user: "{{ ssh_user }}"

  tasks:
  - import_role:
      name: sat6-install
    tags: ['install']
  - import_role:
      name: sat6-configure
    tags: ['configure']
  - import_role:
      name: sat6-post-configure
    tags: ['post']
