---
- name: Debootstrap Instance
  hosts: instance
  become: true
  gather_facts: true
  remote_user: "{{ ssh_user }}"

  tasks:
  - import_role:
      name: sat6-debootstrap
    tags: ['deboostrap']

- name: Remove instance
  hosts: server
  become: true
  gather_facts: no

  tasks:
  - import_role:
      name: osp-stack-delete
    tags: ['undeploy']

