---
- name: Deploy new client
  hosts: server
  become: true
  gather_facts: true
  remote_user: "{{ ssh_user }}"

  tasks:
  - import_role:
      name: osp-stack-create
  - import_role:
      name: osp-inventory
    tags: ['deploy']

- name: Bootstrap Instance
  hosts: instance
  become: true
  gather_facts: true
  remote_user: "{{ ssh_user }}"

  tasks:
  - import_role:
      name: sat6-bootstrap
    tags: ['boostrap']
