- name: Refresh Capsule
  command: hammer capsule refresh-features --id=1

- name: Set download policy
  command: hammer settings set --name default_download_policy --value on_demand

- name: Check if manifest file exists
  stat:
    path: "{{ manifest_file }}"
  register: stat_result

- name: Upload Satellite Manifest
  command: hammer subscription upload --organization {{ org }} --file {{ manifest_file }}
  when: stat_result.stat.exists == True

-name: Refresh manifest
  command: hammer subscription refresh-manifest --organization {{ org }}

- name: Load OpenScap
  command: foreman-rake foreman_openscap:bulk_upload:default

- name: Create puppet environment directory
  file:
    path: /etc/puppet/environments/production/modules
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: 0775

- name: Enable RHEL 7 Server Repository
  command: hammer repository-set enable --organization {{ org }} --product 'Red Hat Enterprise Linux Server' --basearch='x86_64' --releasever='7Server' --name 'Red Hat Enterprise Linux 7 Server (RPMs)'

- name: Syncronize RHEL 7 Server Repository
  command: time hammer repository synchronize --organization "$ORG" --product 'Red Hat Enterprise Linux Server'  --name  'Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server' 2>/dev/null
  register: rhel7_server_output

- debug:
    msg: "{{ rhel7_server_output }}"

- name: Enable Satellite 6 Tools Repository
  command: hammer repository-set enable --organization {{ org }} --product 'Red Hat Enterprise Linux Server' --basearch='x86_64' --name 'Red Hat Satellite Tools 6.3 (for RHEL 7 Server) (RPMs)'

- name: Synchronize Satellite 6 Tools Repository
  command: time hammer repository synchronize --organization {{ org }} --product 'Red Hat Enterprise Linux Server'  --name  'Red Hat Satellite Tools 6.3 for RHEL 7 Server RPMs x86_64'
  register: satellite6_tools_output

- debug
    msg: "{{ satellite6_tools_output }}"

- name: Enable Software Collections Repository
  command: hammer repository-set enable --organization {{ org }} --product 'Red Hat Software Collections for RHEL Server' --basearch='x86_64' --releasever='7Server' --name 'Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server'

- name: Synchronize Satellite 6 Software Collections Repository
  command: time hammer repository synchronize --organization {{ org }} --product 'Red Hat Software Collections for RHEL Server'  --name  'Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server' 2>/dev/null
  register: software_collections_output

- debug:
    msg: "{{ software_collections_output }}"

- name: Create Product for Puppet Forge
  command: hammer product create --name='Puppet Forge' --organization {{ org }}

- name: Create repository for puppet forge
  command: hammer repository create  --organization {{ org }} --name='Modules' --product='Puppet Forge' --content-type='puppet' --publish-via-http=true --url=http://forge.puppetlabs.com/

- name: Synchronize puppet forge repository
  command: time hammer repository synchronize --organization {{ org }} --product 'Puppet Forge'  --name  'Modules' 2>/dev/null
  register: puppet_forge_output

- debug:
    msg: "{{ puppet_forge_output }}"

- name: Create a daily sync plan
  command: hammer sync-plan create --name "daily sync" --enabled=true --interval daily --organization $ORG --sync-date "2018-05-01 01:00:00"

- name: Create Development Lifecycle Environment
  command: hammer lifecycle-environment create --organization {{ org }} --description 'Development' --name 'Development' --label development --prior Library

- name: Create test Lifecycle Environment
  command: hammer lifecycle-environment create --organization {{ org }} --description 'Test' --name 'Test' --label test --prior 'Development'

- name: Create Production Lifecycle Environment
  command: hammer lifecycle-environment create --organization {{ org }} --description 'Production' --name 'Production' --label production --prior 'Test'

- name: Create Staging Lifecycle Environment
  command: hammer lifecycle-environment create --organization {{ org }} --description 'Latest packages without staging' --name 'UnStaged' --label unstaged --prior Library

- name: Create RHEL Base Content View
  command: hammer content-view create --organization {{ org }} --name 'RHEL7_Base' --label rhel7_base --description 'Core Build for RHEL 7'

- name: Add RHEL7 Server to Base content view
  command:  hammer content-view add-repository --organization {{ org }} --name 'RHEL7_Base' --product 'Red Hat Enterprise Linux Server' --repository 'Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server'

- name: Add Satellite tools to base content view
  command: hammer content-view add-repository --organization {{ org }} --name 'RHEL7_Base' --product 'Red Hat Enterprise Linux Server' --repository 'Red Hat Satellite Tools 6.3 for RHEL 7 Server RPMs x86_64'

- name: Add puppet tools to base content view
  command: hammer content-view add-repository --organization {{ org }} --name 'RHEL7_Base' --product 'Red Hat Enterprise Linux Server' --repository 'Red Hat Satellite Tools 6.3 - Puppet 4 for RHEL 7 Server RPMs x86_64'

- name: Add stdlib module to base content view
  command: hammer content-view puppet-module add --organization {{ org }} --content-view RHEL7_Base --author puppetlabs --name stdlib

- name: Add concat puppet module to base content view
  command: hammer content-view puppet-module add --organization {{ org }} --content-view RHEL7_Base --author puppetlabs --name concat

- name: Add ntp puppet module to base content view
  command: hammer content-view puppet-module add --organization {{ org }} --content-view RHEL7_Base --author puppetlabs --name ntp

- name: add ssh puppet module to base content view
  command: hammer content-view puppet-module add --organization {{ org }} --content-view RHEL7_Base --author saz --name ssh

- name: Publish content view
  command: time hammer content-view publish --organization {{ org }} --name RHEL7_Base --description 'Initial Publishing' 2>/dev/null

- name: Promote content view to stage
  command: time hammer content-view version promote --organization {{ org }} --content-view RHEL7_Base --to-lifecycle-environment UnStaged  2>/dev/null

- name: Create activation key:
  command: hammer activation-key create --organization="{{ org }}" --name="rhel7-base" --unlimited-hosts --lifecycle-environment='UnStaged' --content-view='RHEL7_Base'
