---
heat_template_version: 2016-10-14

description:
  An instance for a DNS service made up of a single master and a set of
  slave services.
  The instances are created with Heat and then configured with Ansible

parameters:
  capsule_count:
    type: number
    description: >
      Number of Satelite Capsules to create.
    default: 0

  master_hostname:
    description: >
      The default prefix for Satellite master hostname
    type: string
    default: "sat6-master"

  capsule_hostname_prefix:
    description: >
      The default prefix for capsule hostnames
    type: string
    default: "sat6-capsule"

  domain_name:
    description: >
      All VMs will be placed in this domain
    type: string

  # Networks to connect to or create
  external_network:
    type: string
    description: >
      The external network that provides floating IP addresses for the nodes
    constraints:
    - custom_constraint: neutron.network

  service_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  service_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  capsule_server_group_policies:
    type: comma_delimited_list
    description: >
      List of policies applied on capsule nodes ServerGroup. By default
      'anti-affinity' policy is used to make sure that each capsule node
      is deployed on a different host. If you use a small/all-in-one openstack
      environment, you may need to disable this e.g. by passing
      '-P capsule_server_group_policies=affinity'.
    default: ['anti-affinity']

  master_image:
    description: >
      The Glance image to use as a base for Satellite Server
    type: string
    constraints:
    - custom_constraint: glance.image

  capsule_image:
    description: >
      The Glance image to use as a base for Satellite Capsules
    type: string
    constraints:
    - custom_constraint: glance.image

  master_flavor:
    description: >
      The name of the OpenStack instance flavor to use for Satellite master
    type: string
    default: m1.small
    constraints:
    - custom_constraint: nova.flavor

  master_flavor:
    description: >
      The name of the OpenStack instance flavor to use for Satellite master
    type: string
    default: m1.medium
    constraints:

  capsule_flavor:
    description: >
      The name of the OpenStack instance flavor to use for Satellite Capsules
    type: string
    default: m1.medium
    constraints:

  # Access to the VMs
  ssh_user:
    type: string
    description: >
      The SSH user available on all nodes.
    default: cloud-user

  ssh_key_name:
    type: string
    description: Name of the SSH keypair registered with Nova
    constraints:
    - custom_constraint: nova.keypair

  master_volume_size:
    type: string
    description: Size of the root volume
    default: 50

  capsule_volume_size:
    type: string
    description: Size of the root volume
    default: 50

resources:

  master:
    type: master.yaml
    properties:
      image: {get_param: master_image}
      master_flavor: {get_param: master_flavor}
      external_network: {get_param: external_network}
      service_network: {get_param: service_network}
      service_subnet: {get_param: service_subnet}
      security_group: {get_resource: master_security_group}
      hostname: {get_param: master_hostname}
      domain_name: {get_param: domain_name}
      ssh_user: {get_param: ssh_user}
      ssh_key_name: {get_param: ssh_key_name}
      volume_size: {get_param: master_volume_size}

  capsules:
    type: capsules.yaml
    properties:
      capsule_count: {get_param: capsule_count}
      image: {get_param: capsule_image}
      capsule_flavor: {get_param: capsule_flavor}
      capsule_server_group_policies: {get_param: capsule_server_group_policies}
      external_network: {get_param: external_network}
      service_network: {get_param: service_network}
      service_subnet: {get_param: service_subnet}
      security_group: {get_resource: capsule_security_group}
      hostname_prefix: {get_param: capsule_hostname_prefix}
      domain_name: {get_param: domain_name}
      ssh_user: {get_param: ssh_user}
      ssh_key_name: {get_param: satellite_ssh_key_name}
      volume_size: {get_param: capsule_volume_size}

  master_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        port_range_min: 443
        port_range_max: 443
      - protocol: tcp
        port_range_min: 8443
        port_range_max: 8443
      - protocol: tcp
        port_range_min: 5646
        port_range_max: 5646
      - protocol: tcp
        port_range_min: 5647
        port_range_max: 5647
      - protocol: tcp
        port_range_min: 8000
        port_range_max: 8000
      - protocol: tcp
        port_range_min: 8140
        port_range_max: 8140
      - protocol: tcp
        port_range_min: 9090
        port_range_max: 9090
      - protocol: tcp
        port_range_min: 5000
        port_range_max: 5000
      - protocol: tcp
        port_range_min: 53
        port_range_max: 53
      - protocol: udp
        port_range_min: 53
        port_range_max: 53
      - protocol: udp
        port_range_min: 67
        port_range_max: 67
      - protocol: udp
        port_range_min: 69
        port_range_max: 69

  capsule_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        port_range_min: 443
        port_range_max: 443
      - protocol: tcp
        port_range_min: 8443
        port_range_max: 8443
      - protocol: tcp
        port_range_min: 5646
        port_range_max: 5646
      - protocol: tcp
        port_range_min: 5647
        port_range_max: 5647
      - protocol: tcp
        port_range_min: 8000
        port_range_max: 8000
      - protocol: tcp
        port_range_min: 8140
        port_range_max: 8140
      - protocol: tcp
        port_range_min: 9090
        port_range_max: 9090
      - protocol: tcp
        port_range_min: 5000
        port_range_max: 5000
      - protocol: tcp
        port_range_min: 53
        port_range_max: 53
      - protocol: udp
        port_range_min: 53
        port_range_max: 53
      - protocol: udp
        port_range_min: 67
        port_range_max: 67
      - protocol: udp
        port_range_min: 69
        port_range_max: 69

outputs:
  master_ip_address:
    value: {get_attr: [master, ip_address]}
  capsule_entries:
    value: {get_attr: [capsules, entries]}

