---
heat_template_version: 2016-10-14

description:
  An instance for a Satellite cluster made up of a master and it's capsule servers
  The instances are created with Heat and then configured with Ansible

parameters:

  external_network:
    type: string
    description: >
      The external network that provides floating IP addresses for the nodes
    constraints:
    - custom_constraint: neutron.network

  service_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  service_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  master_hostname:
    description: >
      The default prefix for Satellite master server hostname
    type: string
    default: "sat6-master"

  capsule_hostname_prefix:
    description: >
      The default prefix for nodes server hostnames
    type: string
    default: "sat6-capsule"

  satellite_domain_name:
    description: >
      All VMs will be placed in this domain
    type: string

  capsule_count:
    type: number
    description: >
      Number of capsule servers to create.
    default: 0

  capsule_server_group_policies:
    type: comma_delimited_list
    description: >
      List of policies applied on capsule nodes ServerGroup. By default
      'anti-affinity' policy is used to make sure that each master node
      is deployed on a different host. If you use a small/all-in-one openstack
      environment, you may need to disable this e.g. by passing
      '-P capsule_server_group_policies=affinity'.
    default: ['anti-affinity']

  master_image:
    description: >
      The Glance image to use as a base for Satellite Master
    type: string
    constraints:
    - custom_constraint: glance.image

  capsule_image:
    description: >
      The Glance image to use as a base for Satellite Capsules
    type: string
    constraints:
    - custom_constraint: glance.image

  master_flavor:
    description: >
      The name of the OpenStack instance flavor to use for master server
    type: string
    default: m1.medium
    constraints:
    - custom_constraint: nova.flavor

  capsule_flavor:
    description: >
      The name of the OpenStack instance flavor to use for capsule servers
    type: string
    default: m1.medium
    constraints:
    - custom_constraint: nova.flavor

  # Access to the VMs
  ssh_user:
    type: string
    description: >
      The SSH user available on all nodes.
    default: cloud-user

  satellite_ssh_key_name:
    type: string
    description: Name of the SSH keypair registered with Nova
    constraints:
    - custom_constraint: nova.keypair

  master_volume_size:
    type: string
    description: Size of the root volume
    default: 50

  capsule_volume_size:
    type: string
    description: Size of the root volume
    default: 50

resources:

  hosts:
    type: hosts.yaml
    properties:
      external_network: {get_param: external_network}
      service_network: {get_param: service_network}
      service_subnet: {get_param: service_subnet}
      master_image: {get_param: master_image}
      capsule_image: {get_param: capsule_image}
      master_flavor: {get_param: master_flavor}
      capsule_flavor: {get_param: capsule_flavor}
      master_hostname: {get_param: master_hostname}
      capsule_hostname_prefix: {get_param: capsule_hostname_prefix}
      capsule_server_group_policies: {get_param: capsule_server_group_policies}
      domain_name: {get_param: satellite_domain_name}
      capsule_count: {get_param: capsule_count}
      ssh_user: {get_param: ssh_user}
      ssh_key_name: {get_param: satellite_ssh_key_name}
      master_volume_size: {get_param: master_volume_size}
      capsule_volume_size: {get_param: capsule_volume_size}

outputs:
  ip_address:
    description: The floating IP address of the OpenShift servers
    value:
      master:
        name: {get_param: master_hostname}
        address: {get_attr: [hosts, master_ip_address]}
      capsules: {get_attr: [hosts, capsule_entries]}
