- name: Remove Host from Satellite
  shell: hammer host delete --name {{ hostname_fqdn }}

- name: Check if {{ stack_name }} stack exists
  command: "openstack stack show {{ stack_name }}"
  ignore_errors: yes
  register: stack_check

- name: Delete heat stack {{ stack_name }}
  stack_delete:
    name: "{{ stack_name }}"
  register: stack_output
  when: stack_check.rc == 0
