- name: Check whether the stack exists already
  command: "openstack stack show {{ stack_name }}"
  register: stack_check

- name: Register stack output
  command: >
    openstack stack output show -f value -c output_value
    {{ stack_name }} ip_address
  register: stack_output_raw

- set_fact:
    stack_output: "{{ stack_output_raw.stdout|from_json }}"

- name: Add the bastion to the inventory
  add_host:
    name: "{{ stack_output.name }}"
    groups: instance,all
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ stack_output.address }}"
